#!/usr/bin/env bash

#-----------------------------------------------------------------------------------------------------------------------
# Delete data from previous runs and set up diretories
#-----------------------------------------------------------------------------------------------------------------------

rm -rf ./compare/*
mkdir -p ./compare ./destination ./source

#-----------------------------------------------------------------------------------------------------------------------
# compare/source-1.txt
#-----------------------------------------------------------------------------------------------------------------------

cd ./source && \
    find . -type d | sort > ../compare/source-1.txt; \
    grep . -r . | sort >> ../compare/source-1.txt; \
    cd ..

#-----------------------------------------------------------------------------------------------------------------------
# compare/logfile-1
#-----------------------------------------------------------------------------------------------------------------------

touch 7-sync.log
cat 7-sync.log | sed 's/^[^a-z]*//gi' > compare/logfile-1.log

#-----------------------------------------------------------------------------------------------------------------------
# compare/stdout-1.txt
#-----------------------------------------------------------------------------------------------------------------------

touch 7-sync.out
cat 7-sync.out > compare/stdout-1.txt

#-----------------------------------------------------------------------------------------------------------------------
# compare/database-1.json
# compare/index.txt
# compare/destination-1.txt
#-----------------------------------------------------------------------------------------------------------------------

mkdir -p temp
cd ./temp && \
    find ../destination -type f -name "*.7z" | xargs "-I{}" --no-run-if-empty 7z x -pa -y "{}" > /dev/null; \
    find ../destination -type f -name "___INDEX___*.7z" | xargs --no-run-if-empty "-I{}" 7z x -pa -y "{}" > /dev/null; \
    touch 7-sync-database.json; \
    cp 7-sync-database.json ../compare/database-1.json; \
    touch 7-sync-file-index.txt; \
    cp 7-sync-file-index.txt ../compare/index-1.txt; \
    rm 7-sync*.*; \
    find . -type d | sort > ../compare/destination-1.txt; \
    grep . -r . | sort >> ../compare/destination-1.txt; \
    cd ..
rm -rf ./temp

#-----------------------------------------------------------------------------------------------------------------------
# Run the synchronization
#-----------------------------------------------------------------------------------------------------------------------

make -C .. dist/7-sync.js
rm -f 7-sync.log 7-sync.out
node ../dist/7-sync.js sync --password=a "$@" | tee 7-sync.out

#-----------------------------------------------------------------------------------------------------------------------
# compare/source-2
#-----------------------------------------------------------------------------------------------------------------------

cd ./source && \
    find . -type d | sort > ../compare/source-2.txt; \
    grep . -r . | sort >> ../compare/source-2.txt; \
    cd ..

#-----------------------------------------------------------------------------------------------------------------------
# compare/logfile-2
#-----------------------------------------------------------------------------------------------------------------------

cat 7-sync.log | sed 's/^[^a-z]*//gi' > compare/logfile-2.log

#-----------------------------------------------------------------------------------------------------------------------
# compare/stdout-2.txt
#-----------------------------------------------------------------------------------------------------------------------

cat 7-sync.out > compare/stdout-2.txt

#-----------------------------------------------------------------------------------------------------------------------
# compare/database-1.json
# compare/index.txt
# compare/destination-1.txt
#-----------------------------------------------------------------------------------------------------------------------

mkdir -p temp
cd ./temp && \
    find ../destination -type f -name "*.7z" | xargs  --no-run-if-empty "-I{}" 7z x -pa -y "{}" > /dev/null; \
    find ../destination -type f -name "___INDEX___*.7z" | xargs  --no-run-if-empty "-I{}" 7z x -pa -y "{}" > /dev/null; \
    touch 7-sync-database.json; \
    cp 7-sync-database.json ../compare/database-2.json; \
    touch 7-sync-file-index.txt; \
    cp 7-sync-file-index.txt ../compare/index-2.txt; \
    rm 7-sync*.*; \
    find . -type d | sort > ../compare/destination-2.txt; \
    grep . -r . | sort >> ../compare/destination-2.txt; \
    cd ..
rm -rf ./temp

#-----------------------------------------------------------------------------------------------------------------------
# Checks
#-----------------------------------------------------------------------------------------------------------------------

diff compare/source-2.txt compare/destination-2.txt > /dev/null
if [ $? != 0 ]; then
    echo
    echo "=====> ERROR: Source and destination differ"
fi

diff compare/source-1.txt compare/source-2.txt > /dev/null
if [ $? != 0 ]; then
    echo
    echo "=====> ERROR: The source has been modified"
fi
